version: '3'
services:
  api:
    build: ./api
    #image: billxuregistry.azurecr.io/xbox-api
    container_name: xbox-api
    platform: linux/amd64
    ports:
     - "3031:3031"
  web:
    build: ./web
    #image: billxuregistry.azurecr.io/xbox-web
    container_name: xbox-web
    platform: linux/amd64
    ports:
     - "80:80"
