version: '3'
services:
  # Traefik reverse proxy
  reverse-proxy:
      image: traefik:v2.8
      restart: on-failure
      command:
          - --api.insecure=true
          - --providers.docker=true
          - --providers.docker.exposedbydefault=false
          - --entrypoints.web.address=:80
      ports:
          - 80:80     # The HTTP port
          - 9000:8080 # The Web UI (enabled by --api), mapped to port 9000 to resolve conflict with client port
      
      volumes:
          - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
      networks:
          - reverse-proxy

  api:
    build: ./api
    #image: billxuregistry.azurecr.io/xbox-api
    container_name: xbox-api
    platform: linux/amd64
    # ports:
    #  - "3031:3031"
    expose:
      - 3031
    networks:
      - reverse-proxy
    labels:
      - "traefik.http.routers.backend.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.enable=true"

  # web:
  #   build: ./web
  #   container_name: xbox-web
  #   expose:
  #     - 8080
  #   networks:
  #     - reverse-proxy
  #   depends_on:
  #     - api
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.frontend.rule=Host(`localhost`)"
  #     - "traefik.http.routers.frontend.entrypoints=web"

networks:
    reverse-proxy:
        driver: bridge